
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dynamic vCard Generator</title>
  <style>
    /* Dark Mode Styling */
    body {
      font-family: Arial, sans-serif;
      background-color: #121212;
      color: #e0e0e0;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }
    .card {
      background-color: #1e1e1e;
      border-radius: 10px;
      width: 300px;
      padding: 20px;
      box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.7);
      text-align: center;
    }
    .profile-img {
      width: 100px;
      height: 100px;
      border-radius: 50%;
      margin: 10px auto;
      display: block;
      border: 2px solid #4CAF50;
    }
    input[type="text"], input[type="tel"], input[type="email"], input[type="url"] {
      width: 100%;
      padding: 10px;
      margin: 10px 0;
      background-color: #333;
      color: #e0e0e0;
      border: none;
      border-radius: 5px;
    }
    button {
      width: 100%;
      padding: 10px;
      background-color: #4CAF50;
      color: white;
      border: none;
      border-radius: 5px;
      font-weight: bold;
      cursor: pointer;
      margin-top: 15px;
      transition: background-color 0.3s ease;
    }
    button:hover {
      background-color: #45a049;
    }
  </style>
</head>
<body>

<div class="card">
  <!-- Profile Image -->
  <img src="profile.jpg" alt="Profile Image" class="profile-img">

  <!-- Contact Form -->
  <form id="vcardForm">
    <input type="text" id="firstName" placeholder="First Name" required>
    <input type="text" id="lastName" placeholder="Last Name" required>
    <input type="tel" id="mobile" placeholder="Mobile Number" required>
    <input type="tel" id="whatsapp" placeholder="WhatsApp Number" required>
    <input type="email" id="email" placeholder="Email Address" required>
    <input type="url" id="website" placeholder="Website URL">
    <input type="text" id="address" placeholder="Address">
    <div class="social-links">
      <input type="url" id="facebook" placeholder="Facebook URL">
      <input type="url" id="instagram" placeholder="Instagram URL">
    </div>
    <button type="button" onclick="generateVCard()">Convert to vCard</button>
  </form>
</div>

<script>
  function generateVCard() {
    const firstName = document.getElementById("firstName").value;
    const lastName = document.getElementById("lastName").value;
    const mobile = document.getElementById("mobile").value;
    const whatsapp = document.getElementById("whatsapp").value;
    const email = document.getElementById("email").value;
    const website = document.getElementById("website").value;
    const address = document.getElementById("address").value;
    const facebook = document.getElementById("facebook").value;
    const instagram = document.getElementById("instagram").value;

    // vCard format with dynamic data
    const vCardData = `
BEGIN:VCARD
VERSION:3.0
N:${lastName};${firstName};;;
FN:${firstName} ${lastName}
TEL;TYPE=CELL:${mobile}
TEL;TYPE=WHATSAPP:${whatsapp}
EMAIL:${email}
URL:${website}
ADR:;;${address};;;
X-SOCIALPROFILE;TYPE=facebook:${facebook}
X-SOCIALPROFILE;TYPE=instagram:${instagram}
END:VCARD
    `.trim();

    // Create a blob from the vCard data
    const blob = new Blob([vCardData], { type: "text/vcard" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = `${firstName}_${lastName}_contact.vcf`;
    link.click();
  }
</script>

</body>
</html>
